name: CI Test & Report to Jira

on:
  push:
    branches: [main, develop, develop2]

jobs:
  test-and-report:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          java-version: 17
          distribution: "temurin"
          cache: "maven"

      - name: Run Maven tests
        run: mvn -B clean test

      - name: Upload JUnit results to Xray (Jira)
        env:
          JIRA_EMAIL: ${{ secrets.JIRA_EMAIL }}
          JIRA_API_TOKEN: ${{ secrets.JIRA_API_TOKEN }}
        run: |
          # Create issue
          ISSUE_KEY=$(curl -s -u "$JIRA_EMAIL:$JIRA_API_TOKEN" \
            -H "Content-Type: application/json" \
            -d '{"fields":{"project":{"key":"ST2N1"},"summary":"Func 1: Test result #${{ github.run_number }}","issuetype":{"name":"Test Execution"}}}' \
            https://software-testing-nhom-1.atlassian.net/rest/api/3/issue | jq -r '.key')

          # Attach report
          curl -s -u "$JIRA_EMAIL:$JIRA_API_TOKEN" \
            -H "X-Atlassian-Token: no-check" \
            -F "file=@target/surefire-reports/TEST-com.example.CalculatorTest.xml" \
            "https://software-testing-nhom-1.atlassian.net/rest/api/3/issue/$ISSUE_KEY/attachments"
