name: CI Test & Report to Jira

on:
  push:
    branches: [ main ]

jobs:
  test-and-report:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          java-version: 17
          distribution: 'temurin'
          cache: 'maven'

      - name: Run Maven tests
        run: mvn -B clean test

      - name: Show Maven repository contents
        run: ls -R ~/.m2/repository/org/apache/maven/plugins/maven-surefire-plugin || echo "Surefire not found"

      - name: Check for Surefire reports
        run: |
          echo "Listing surefire-reports..."
          ls -R target || echo "No target directory found"
          find . -type f -name "TEST-*.xml" || echo "No TEST-*.xml files found"

      - name: Upload JUnit results to Xray (Jira)
        env:
          XRAY_CLIENT_ID: ${{ secrets.XRAY_CLIENT_ID }}
          XRAY_CLIENT_SECRET: ${{ secrets.XRAY_CLIENT_SECRET }}
        run: |
          TOKEN=$(curl -s -X POST https://xray.cloud.getxray.app/api/v2/authenticate \
            -H "Content-Type: application/json" \
            -d "{\"client_id\":\"$XRAY_CLIENT_ID\",\"client_secret\":\"$XRAY_CLIENT_SECRET\"}" | tr -d '"')

          for f in target/surefire-reports/*.xml; do
            echo "Uploading $f"
            curl -s -X POST https://xray.cloud.getxray.app/api/v2/import/execution/junit \
              -H "Authorization: Bearer $TOKEN" \
              -F "file=@$f"
          done
